#!/bin/bash

resize() {
    convert "originals/$1" \
        -define png:compression-strategy=1 \
        -strip \
        -define png:compression-filter=5 \
        -define png:compression-level=9 \
        -unsharp 0.25x0.25+8+0.065 \
        -filter lanczos \
        -set filename:base "%[base]" "%[filename:base].png" 
}

# Grass
resize "grass.png[x28]"

# Pony
resize "pony*.png[100x]"

# Star
resize "star*.png[20x]"

# Rainbow
resize "rainbow*.png[80x]"

